set(
    REQUIRED_PREPROCESSOR_DEFINITIONS
    ONU_VERSION_MAJOR=${ONIUN_VERSION_MAJOR}
    ONU_VERSION_MINOR=${ONIUN_VERSION_MINOR}
    ONU_VERSION_PATCH=${ONIUN_VERSION_PATCH}
    ONU_VERSION_STR="${ONIUN_VERSION_STR}"
)
set(
    PLATFORM_SPECIFIC_COMPILER_OPTIONS
)

# Platform specific definitions
if (WIN32)
    list(APPEND REQUIRED_PREPROCESSOR_DEFINITIONS ONU_PLATFORM_WINDOWS)
    if (MSVC)
        list(APPEND PLATFORM_SPECIFIC_COMPILER_OPTIONS "/utf-8")
        list(APPEND REQUIRED_PREPROCESSOR_DEFINITIONS "_CRT_SECURE_NO_WARNINGS")
    endif()
elseif (UNIX)
    list(APPEND REQUIRED_PREPROCESSOR_DEFINITIONS ONU_PLATFORM_UNIX)
    if (APPLE)
        list(APPEND REQUIRED_PREPROCESSOR_DEFINITIONS ONU_PLATFORM_APPLE)
    else()
        list(APPEND REQUIRED_PREPROCESSOR_DEFINITIONS ONU_PLATFORM_LINUX)
    endif()
endif()

